H_inverted_up_trim: -4139
altitude_trim: 170
H_pitch_center_trim: 46
H_right_trim: -2045
H_inverted_left_trim: -4471
H_inverted_down_trim: -4098
H_left_trim: 2031
H_down_trim: -2056
H_inverted_center_trim: 4467
H_roll_center_trim: -28
H_up_trim: 2019
H_inverted_right_trim: -3963
